# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ivanchetvergov/prac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ivanchetvergov/prac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivanchetvergov/prac/CMakeFiles /home/ivanchetvergov/prac//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivanchetvergov/prac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bench_static_it_O0

# Build rule for target.
bench_static_it_O0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_it_O0
.PHONY : bench_static_it_O0

# fast build rule for target.
bench_static_it_O0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O0.dir/build.make CMakeFiles/bench_static_it_O0.dir/build
.PHONY : bench_static_it_O0/fast

#=============================================================================
# Target rules for targets named bench_static_rec_O0

# Build rule for target.
bench_static_rec_O0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_rec_O0
.PHONY : bench_static_rec_O0

# fast build rule for target.
bench_static_rec_O0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O0.dir/build.make CMakeFiles/bench_static_rec_O0.dir/build
.PHONY : bench_static_rec_O0/fast

#=============================================================================
# Target rules for targets named bench_shared_it_O0

# Build rule for target.
bench_shared_it_O0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_it_O0
.PHONY : bench_shared_it_O0

# fast build rule for target.
bench_shared_it_O0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O0.dir/build.make CMakeFiles/bench_shared_it_O0.dir/build
.PHONY : bench_shared_it_O0/fast

#=============================================================================
# Target rules for targets named bench_shared_rec_O0

# Build rule for target.
bench_shared_rec_O0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_rec_O0
.PHONY : bench_shared_rec_O0

# fast build rule for target.
bench_shared_rec_O0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O0.dir/build.make CMakeFiles/bench_shared_rec_O0.dir/build
.PHONY : bench_shared_rec_O0/fast

#=============================================================================
# Target rules for targets named bench_static_it_O1

# Build rule for target.
bench_static_it_O1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_it_O1
.PHONY : bench_static_it_O1

# fast build rule for target.
bench_static_it_O1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O1.dir/build.make CMakeFiles/bench_static_it_O1.dir/build
.PHONY : bench_static_it_O1/fast

#=============================================================================
# Target rules for targets named bench_static_rec_O1

# Build rule for target.
bench_static_rec_O1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_rec_O1
.PHONY : bench_static_rec_O1

# fast build rule for target.
bench_static_rec_O1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O1.dir/build.make CMakeFiles/bench_static_rec_O1.dir/build
.PHONY : bench_static_rec_O1/fast

#=============================================================================
# Target rules for targets named bench_shared_it_O1

# Build rule for target.
bench_shared_it_O1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_it_O1
.PHONY : bench_shared_it_O1

# fast build rule for target.
bench_shared_it_O1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O1.dir/build.make CMakeFiles/bench_shared_it_O1.dir/build
.PHONY : bench_shared_it_O1/fast

#=============================================================================
# Target rules for targets named bench_shared_rec_O1

# Build rule for target.
bench_shared_rec_O1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_rec_O1
.PHONY : bench_shared_rec_O1

# fast build rule for target.
bench_shared_rec_O1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O1.dir/build.make CMakeFiles/bench_shared_rec_O1.dir/build
.PHONY : bench_shared_rec_O1/fast

#=============================================================================
# Target rules for targets named bench_static_it_O2

# Build rule for target.
bench_static_it_O2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_it_O2
.PHONY : bench_static_it_O2

# fast build rule for target.
bench_static_it_O2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O2.dir/build.make CMakeFiles/bench_static_it_O2.dir/build
.PHONY : bench_static_it_O2/fast

#=============================================================================
# Target rules for targets named bench_static_rec_O2

# Build rule for target.
bench_static_rec_O2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_rec_O2
.PHONY : bench_static_rec_O2

# fast build rule for target.
bench_static_rec_O2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O2.dir/build.make CMakeFiles/bench_static_rec_O2.dir/build
.PHONY : bench_static_rec_O2/fast

#=============================================================================
# Target rules for targets named bench_shared_it_O2

# Build rule for target.
bench_shared_it_O2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_it_O2
.PHONY : bench_shared_it_O2

# fast build rule for target.
bench_shared_it_O2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O2.dir/build.make CMakeFiles/bench_shared_it_O2.dir/build
.PHONY : bench_shared_it_O2/fast

#=============================================================================
# Target rules for targets named bench_shared_rec_O2

# Build rule for target.
bench_shared_rec_O2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_rec_O2
.PHONY : bench_shared_rec_O2

# fast build rule for target.
bench_shared_rec_O2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O2.dir/build.make CMakeFiles/bench_shared_rec_O2.dir/build
.PHONY : bench_shared_rec_O2/fast

#=============================================================================
# Target rules for targets named bench_static_it_Os

# Build rule for target.
bench_static_it_Os: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_it_Os
.PHONY : bench_static_it_Os

# fast build rule for target.
bench_static_it_Os/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_Os.dir/build.make CMakeFiles/bench_static_it_Os.dir/build
.PHONY : bench_static_it_Os/fast

#=============================================================================
# Target rules for targets named bench_static_rec_Os

# Build rule for target.
bench_static_rec_Os: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_static_rec_Os
.PHONY : bench_static_rec_Os

# fast build rule for target.
bench_static_rec_Os/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_Os.dir/build.make CMakeFiles/bench_static_rec_Os.dir/build
.PHONY : bench_static_rec_Os/fast

#=============================================================================
# Target rules for targets named bench_shared_it_Os

# Build rule for target.
bench_shared_it_Os: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_it_Os
.PHONY : bench_shared_it_Os

# fast build rule for target.
bench_shared_it_Os/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_Os.dir/build.make CMakeFiles/bench_shared_it_Os.dir/build
.PHONY : bench_shared_it_Os/fast

#=============================================================================
# Target rules for targets named bench_shared_rec_Os

# Build rule for target.
bench_shared_rec_Os: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_shared_rec_Os
.PHONY : bench_shared_rec_Os

# fast build rule for target.
bench_shared_rec_Os/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_Os.dir/build.make CMakeFiles/bench_shared_rec_Os.dir/build
.PHONY : bench_shared_rec_Os/fast

#=============================================================================
# Target rules for targets named bench_dlopen_it

# Build rule for target.
bench_dlopen_it: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_dlopen_it
.PHONY : bench_dlopen_it

# fast build rule for target.
bench_dlopen_it/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_it.dir/build.make CMakeFiles/bench_dlopen_it.dir/build
.PHONY : bench_dlopen_it/fast

#=============================================================================
# Target rules for targets named bench_dlopen_rec

# Build rule for target.
bench_dlopen_rec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_dlopen_rec
.PHONY : bench_dlopen_rec

# fast build rule for target.
bench_dlopen_rec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_rec.dir/build.make CMakeFiles/bench_dlopen_rec.dir/build
.PHONY : bench_dlopen_rec/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named count_size

# Build rule for target.
count_size: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 count_size
.PHONY : count_size

# fast build rule for target.
count_size/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/count_size.dir/build.make CMakeFiles/count_size.dir/build
.PHONY : count_size/fast

#=============================================================================
# Target rules for targets named parse_and_build_graph

# Build rule for target.
parse_and_build_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_and_build_graph
.PHONY : parse_and_build_graph

# fast build rule for target.
parse_and_build_graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_and_build_graph.dir/build.make CMakeFiles/parse_and_build_graph.dir/build
.PHONY : parse_and_build_graph/fast

#=============================================================================
# Target rules for targets named full_cycle

# Build rule for target.
full_cycle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 full_cycle
.PHONY : full_cycle

# fast build rule for target.
full_cycle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/full_cycle.dir/build.make CMakeFiles/full_cycle.dir/build
.PHONY : full_cycle/fast

#=============================================================================
# Target rules for targets named student_db

# Build rule for target.
student_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 student_db
.PHONY : student_db

# fast build rule for target.
student_db/fast:
	$(MAKE) $(MAKESILENT) -f database_app/CMakeFiles/student_db.dir/build.make database_app/CMakeFiles/student_db.dir/build
.PHONY : student_db/fast

tests/bench_dlopen_it.o: tests/bench_dlopen_it.c.o
.PHONY : tests/bench_dlopen_it.o

# target to build an object file
tests/bench_dlopen_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_it.dir/build.make CMakeFiles/bench_dlopen_it.dir/tests/bench_dlopen_it.c.o
.PHONY : tests/bench_dlopen_it.c.o

tests/bench_dlopen_it.i: tests/bench_dlopen_it.c.i
.PHONY : tests/bench_dlopen_it.i

# target to preprocess a source file
tests/bench_dlopen_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_it.dir/build.make CMakeFiles/bench_dlopen_it.dir/tests/bench_dlopen_it.c.i
.PHONY : tests/bench_dlopen_it.c.i

tests/bench_dlopen_it.s: tests/bench_dlopen_it.c.s
.PHONY : tests/bench_dlopen_it.s

# target to generate assembly for a file
tests/bench_dlopen_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_it.dir/build.make CMakeFiles/bench_dlopen_it.dir/tests/bench_dlopen_it.c.s
.PHONY : tests/bench_dlopen_it.c.s

tests/bench_dlopen_rec.o: tests/bench_dlopen_rec.c.o
.PHONY : tests/bench_dlopen_rec.o

# target to build an object file
tests/bench_dlopen_rec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_rec.dir/build.make CMakeFiles/bench_dlopen_rec.dir/tests/bench_dlopen_rec.c.o
.PHONY : tests/bench_dlopen_rec.c.o

tests/bench_dlopen_rec.i: tests/bench_dlopen_rec.c.i
.PHONY : tests/bench_dlopen_rec.i

# target to preprocess a source file
tests/bench_dlopen_rec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_rec.dir/build.make CMakeFiles/bench_dlopen_rec.dir/tests/bench_dlopen_rec.c.i
.PHONY : tests/bench_dlopen_rec.c.i

tests/bench_dlopen_rec.s: tests/bench_dlopen_rec.c.s
.PHONY : tests/bench_dlopen_rec.s

# target to generate assembly for a file
tests/bench_dlopen_rec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_dlopen_rec.dir/build.make CMakeFiles/bench_dlopen_rec.dir/tests/bench_dlopen_rec.c.s
.PHONY : tests/bench_dlopen_rec.c.s

tests/bench_it.o: tests/bench_it.c.o
.PHONY : tests/bench_it.o

# target to build an object file
tests/bench_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O0.dir/build.make CMakeFiles/bench_static_it_O0.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O0.dir/build.make CMakeFiles/bench_shared_it_O0.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O1.dir/build.make CMakeFiles/bench_static_it_O1.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O1.dir/build.make CMakeFiles/bench_shared_it_O1.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O2.dir/build.make CMakeFiles/bench_static_it_O2.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O2.dir/build.make CMakeFiles/bench_shared_it_O2.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_Os.dir/build.make CMakeFiles/bench_static_it_Os.dir/tests/bench_it.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_Os.dir/build.make CMakeFiles/bench_shared_it_Os.dir/tests/bench_it.c.o
.PHONY : tests/bench_it.c.o

tests/bench_it.i: tests/bench_it.c.i
.PHONY : tests/bench_it.i

# target to preprocess a source file
tests/bench_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O0.dir/build.make CMakeFiles/bench_static_it_O0.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O0.dir/build.make CMakeFiles/bench_shared_it_O0.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O1.dir/build.make CMakeFiles/bench_static_it_O1.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O1.dir/build.make CMakeFiles/bench_shared_it_O1.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O2.dir/build.make CMakeFiles/bench_static_it_O2.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O2.dir/build.make CMakeFiles/bench_shared_it_O2.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_Os.dir/build.make CMakeFiles/bench_static_it_Os.dir/tests/bench_it.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_Os.dir/build.make CMakeFiles/bench_shared_it_Os.dir/tests/bench_it.c.i
.PHONY : tests/bench_it.c.i

tests/bench_it.s: tests/bench_it.c.s
.PHONY : tests/bench_it.s

# target to generate assembly for a file
tests/bench_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O0.dir/build.make CMakeFiles/bench_static_it_O0.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O0.dir/build.make CMakeFiles/bench_shared_it_O0.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O1.dir/build.make CMakeFiles/bench_static_it_O1.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O1.dir/build.make CMakeFiles/bench_shared_it_O1.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_O2.dir/build.make CMakeFiles/bench_static_it_O2.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_O2.dir/build.make CMakeFiles/bench_shared_it_O2.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_it_Os.dir/build.make CMakeFiles/bench_static_it_Os.dir/tests/bench_it.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_it_Os.dir/build.make CMakeFiles/bench_shared_it_Os.dir/tests/bench_it.c.s
.PHONY : tests/bench_it.c.s

tests/bench_rec.o: tests/bench_rec.c.o
.PHONY : tests/bench_rec.o

# target to build an object file
tests/bench_rec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O0.dir/build.make CMakeFiles/bench_static_rec_O0.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O0.dir/build.make CMakeFiles/bench_shared_rec_O0.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O1.dir/build.make CMakeFiles/bench_static_rec_O1.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O1.dir/build.make CMakeFiles/bench_shared_rec_O1.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O2.dir/build.make CMakeFiles/bench_static_rec_O2.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O2.dir/build.make CMakeFiles/bench_shared_rec_O2.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_Os.dir/build.make CMakeFiles/bench_static_rec_Os.dir/tests/bench_rec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_Os.dir/build.make CMakeFiles/bench_shared_rec_Os.dir/tests/bench_rec.c.o
.PHONY : tests/bench_rec.c.o

tests/bench_rec.i: tests/bench_rec.c.i
.PHONY : tests/bench_rec.i

# target to preprocess a source file
tests/bench_rec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O0.dir/build.make CMakeFiles/bench_static_rec_O0.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O0.dir/build.make CMakeFiles/bench_shared_rec_O0.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O1.dir/build.make CMakeFiles/bench_static_rec_O1.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O1.dir/build.make CMakeFiles/bench_shared_rec_O1.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O2.dir/build.make CMakeFiles/bench_static_rec_O2.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O2.dir/build.make CMakeFiles/bench_shared_rec_O2.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_Os.dir/build.make CMakeFiles/bench_static_rec_Os.dir/tests/bench_rec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_Os.dir/build.make CMakeFiles/bench_shared_rec_Os.dir/tests/bench_rec.c.i
.PHONY : tests/bench_rec.c.i

tests/bench_rec.s: tests/bench_rec.c.s
.PHONY : tests/bench_rec.s

# target to generate assembly for a file
tests/bench_rec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O0.dir/build.make CMakeFiles/bench_static_rec_O0.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O0.dir/build.make CMakeFiles/bench_shared_rec_O0.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O1.dir/build.make CMakeFiles/bench_static_rec_O1.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O1.dir/build.make CMakeFiles/bench_shared_rec_O1.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_O2.dir/build.make CMakeFiles/bench_static_rec_O2.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_O2.dir/build.make CMakeFiles/bench_shared_rec_O2.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_static_rec_Os.dir/build.make CMakeFiles/bench_static_rec_Os.dir/tests/bench_rec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_shared_rec_Os.dir/build.make CMakeFiles/bench_shared_rec_Os.dir/tests/bench_rec.c.s
.PHONY : tests/bench_rec.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bench"
	@echo "... count_size"
	@echo "... full_cycle"
	@echo "... parse_and_build_graph"
	@echo "... bench_dlopen_it"
	@echo "... bench_dlopen_rec"
	@echo "... bench_shared_it_O0"
	@echo "... bench_shared_it_O1"
	@echo "... bench_shared_it_O2"
	@echo "... bench_shared_it_Os"
	@echo "... bench_shared_rec_O0"
	@echo "... bench_shared_rec_O1"
	@echo "... bench_shared_rec_O2"
	@echo "... bench_shared_rec_Os"
	@echo "... bench_static_it_O0"
	@echo "... bench_static_it_O1"
	@echo "... bench_static_it_O2"
	@echo "... bench_static_it_Os"
	@echo "... bench_static_rec_O0"
	@echo "... bench_static_rec_O1"
	@echo "... bench_static_rec_O2"
	@echo "... bench_static_rec_Os"
	@echo "... student_db"
	@echo "... tests/bench_dlopen_it.o"
	@echo "... tests/bench_dlopen_it.i"
	@echo "... tests/bench_dlopen_it.s"
	@echo "... tests/bench_dlopen_rec.o"
	@echo "... tests/bench_dlopen_rec.i"
	@echo "... tests/bench_dlopen_rec.s"
	@echo "... tests/bench_it.o"
	@echo "... tests/bench_it.i"
	@echo "... tests/bench_it.s"
	@echo "... tests/bench_rec.o"
	@echo "... tests/bench_rec.i"
	@echo "... tests/bench_rec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

